### ISSUE TITLE
Fill in Deck 1 - The Whole Game slide

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/workshops#11]
It is still empty
<img width="1347" alt="Screen Shot 2022-06-13 at 2 53 41 PM" src="https://user-images.githubusercontent.com/19150088/173424480-8b3e5444-29a0-4849-850a-89846fef6ab4.png">

**Comment by juliasilge** [comment]
@topepo Whenever you want to get over these slides that would be great. PR or just the outline would be great!
