### ISSUE TITLE
2023 - conf - direct users to install Rtools

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workshops#148]
This will be surfaced when people `install.packages("pak")` if people don't have it installed, but worth calling out that it may be an issue and how to address it.

**Comment by simonpcouch** [comment]
If modeldatatoo makes it to CRAN and all we need to use to install packages is `install.packages()` then we may be able to get around this. Otherwise, may be worth linking to https://cran.r-project.org/bin/windows/Rtools/rtools43/rtools.html in the install code. Related to #187.

**Comment by topepo** [comment]
With #245 we won't be using modeldatatoo. Original problem still remains though.

**Comment by hfrick** [comment]
I think it'd be worth linking to the CRAN page of Rtools 👍
