### ISSUE TITLE
2023 conf - whole game slides

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/workshops#149]
This is more of a personal opinion

I think it would be neat if the 3 models (diamonds) were contained in a container to show it is "a pool of possible models"

**Comment by hfrick** [comment]
I was also thinking about removing the arrow from training to the decision tree in `model-n` to reduce the chances of anyone looking at this and assuming we'd be fitting all the models to the entire training set. Alternatively, we could take out that stage altogether.
