### ISSUE TITLE
2023 - conf - describing taxi "pre-processing"

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workshops#150]
The `mutate(month = factor(...))` and `drop_na()` steps were both described as no-no's when showing the slide. Might be worth thinking about 1) whether we want to do both of these (or in the internals of `data_taxi()`?) and/or 2) how we might describe when why this is fine for the purposes of the workshop.

**Comment by simonpcouch** [comment]
My take here is that we ought to do all possible prep—`mutate(month = ...)`, `drop_na()`, maybe even column selection—in modeldatatoo and then use `data_taxi()` output directly. What are others' thoughts?

**Comment by EmilHvitfeldt** [comment]
I'm all 👍 for doing all the prep in {modeldatatoo}

**Comment by hfrick** [comment]
So we'd put two versions of the taxi data into modeldatatoo, one "as is" and one preprocessed for the intro workshop?

**Comment by hfrick** [comment]
Ah, I see! Yeah, I am okay with that 👍
