### ISSUE TITLE
using modeldatatoo

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workshops#153]
pins is a tricky install for some folks with locked-down laptops, and modeldatatoo needs it for the `data_taxi()` backend. 

There may be ways to get around that in modeldatatoo, but also maybe another argument for urging folks to transition to the cloud instance🙈

**Comment by EmilHvitfeldt** [comment]
related to https://github.com/tidymodels/workshops/issues/148

**Comment by EmilHvitfeldt** [comment]
And honestly, there are two easy low tech solutions.

- Having direct links people can use to download the `.csv`/`.rds` file themselves
- We bring a couple of flash drives with the data sets on them

**Comment by hfrick** [comment]
closed in #245
