### ISSUE TITLE
exercise for defining a model spec 

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workshops#156]
Some commentary that, in the first exercise for "What Makes a Model":

```
Run the tree_spec chunk in your .qmd.

Edit this code to use a different model.
```

is a bit too open-ended. We may want to revert back to a more direct prompt.

Maybe we could have people adjust to an engine that requires an extension package and have them follow the prompts in the resulting message?

**Comment by hfrick** [comment]
Or we split it into two levels a la: 

```
Edit this code to use a logistic regression model.

Extension/Challenge: Try using a conditional inference tree as implemented in the partykit package by changing the engine.
```
