### ISSUE TITLE
increase width of `rpart.plot` outplot

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workshops#158]
This rpart.plot is quite difficult to see when scaled down to accommodate the text.

https://github.com/tidymodels/workshops/blob/4a6d2b911ac2932e508324baac5082d99dabaf65/slides/03-what-makes-a-model.qmd#L311-L316

**Comment by EmilHvitfeldt** [comment]
duplicate of https://github.com/tidymodels/workshops/issues/157
