### ISSUE TITLE
font size: all models are wrong, but some are useful

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/workshops#159]
This slide should have the title font size reduced so it fits on one line

**Comment by simonpcouch** [comment]
I do kind of appreciate them, and don't think they draw too much attention if you aren't looking for them. Not a strong opinion though, and I'm fine if we decide to do away with these. :)

**Comment by simonpcouch** [comment]
Agreed that this ought to fit on one line, though I'm seeing locally that it does.🤔

**Comment by EmilHvitfeldt** [comment]
That is weird, I'm not seeing it anymore, but I saw it when it was presented

**Comment by simonpcouch** [comment]
This could possibly have been a hardware (Max's env or the projector setup?) hiccup, so I'll go ahead and close.
