### ISSUE TITLE
style: line numbers

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/workshops#160]
personal opinion: I don't think the line numbers in the slides add much. And would be fine with disabling them. Especially since we use line highlighting anyways

**Comment by simonpcouch** [comment]
I do kind of appreciate them, and don't think they draw too much attention if you aren't looking for them. Not a strong opinion though, and I'm fine if we decide to do away with these. :)

**Comment by hfrick** [comment]
I lean towards keeping them because they also give the learners a tool to be precise about which part of the code they are referring to with a question or comment.

**Comment by simonpcouch** [comment]
It sounds like changing these might be a lateral move pedagogically. I'll go ahead and close.💐
