### ISSUE TITLE
(nearly) back-to-back exercises in "What makes a model"

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workshops#162]
There's only one short slide between exercises when introducing `predict()` in "What makes your model"

https://github.com/tidymodels/workshops/blob/4a6d2b911ac2932e508324baac5082d99dabaf65/slides/03-what-makes-a-model.qmd#L500-L511

https://github.com/tidymodels/workshops/blob/4a6d2b911ac2932e508324baac5082d99dabaf65/slides/03-what-makes-a-model.qmd#L527-L535

**Comment by hfrick** [comment]
Do you think we should be saying more in between? Or did you just note that we play it back to learners relatively quickly here? I don't think that fast return to an exercise is necessarily bad.
