### ISSUE TITLE
Linking the whole game diagrams to code

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workshops#172]
Andrew proposed possibly, in addition to showing portions of the whole game diagram as we progress through, also including the actual (pseudo?)code corresponding to different labels in the diagrams.

**Comment by hfrick** [comment]
Totally agree that this could be super useful. We'd need to find an execution of this idea though where we don't overload the diagram.

**Comment by simonpcouch** [comment]
Will close in favor of #171 as a venue to discuss whether we want to modify the "in-progress" whole game slides.
