### ISSUE TITLE
the "baseline" model

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workshops#199]
Consider whether a transformation of the `distance` column might make teaching logistic regression + visualizing that sigmoid a bit easier, or whether we might want to instead use k-nearest neighbors.

**Comment by simonpcouch** [comment]
Just spent a bit of time trying to find a parameterization that makes that curve a bit more dramatic / familiar and was unsuccessful.🙃 cc @hfrick @EmilHvitfeldt

**Comment by hfrick** [comment]
linking this with #150
