### ISSUE TITLE
Deck 3 - Model explanations

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/workshops#21]
I think my biggest meta comment about deck 3 is that I feel like we don't explain the models we are talking about.

We said that our prereq for this workshop is basic tidyverse knowledge, so I don't think we can assume people know how rpart works.

Like, in this slide we fit an rpart model and then the next few slides use `predict()` on it and show some of the rpart plotting methods, but I don't see a place where we really stop and discuss what this kind of model does

<img width="1375" alt="Screen Shot 2022-06-14 at 10 17 27 AM" src="https://user-images.githubusercontent.com/19150088/173600415-48052e2e-8013-436a-9b58-bc6ef31b939b.png">

**Comment by juliasilge** [comment]
Yep, I had been leaning toward us having some specific things we want to say in speaker notes on decision trees, random forest, linear models, and xgboost, but @topepo was leaning toward a single slide for each of these, which I am not opposed to.

**Comment by DavisVaughan** [comment]
+1 to having a dedicated slide talking about each model we plan on using

**Comment by juliasilge** [comment]
It might be nice to put explanations of linear models + decision tree in deck 3 interspersed with the slides that do these:

![image](https://user-images.githubusercontent.com/12505835/173671938-41c25fd5-af2d-456d-ba77-2b9a98c1b766.png)
![image](https://user-images.githubusercontent.com/12505835/173671962-2172b4cf-8038-4c8c-9851-f94700e89851.png)

Then reiterate what decision tree does and extend to random forest in deck 4 around here:

> # Decision tree 🌳
>
> # Random forest 🌳🌲🌴🌵🌴🌳🌳🌴🌲🌵🌴🌲🌳🌴🌳🌵🌵🌴🌲🌲🌳🌴🌳🌴🌲🌴🌵🌴🌲🌴🌵🌲

And reiterate a linear model + introduce xgboost (related back to other tree based models) on Day 2.

**Comment by topepo** [comment]
My initial comment was to have a few slides but we were worried about too much content and it was suggested that it should be one slide. 

For the NYR slides, I have a single classification tree slide that shows a tree. From there, we can discuss the growing and pruning phases as well as tuning parameters. 

For boosting, those slides have:

```
# Boosting

Boosting methods fit a sequence of tree-based models. 

Each is dependent on the last and tries to compensate to any poor results in the previous models

* This is akin to gradient-based steepest ascent methods from calculus. 

Most modern boosting methods have _a lot_ of tuning parameters.
 * For tree growth and pruning (`min_n`, `max_depth`. etc).
 * For boosting (`trees`, `stop_iter`, `learn_rate`)

We'll use _early stopping_ where we stop boosting when a few iterations produces consecutively worse results. 
```

**Comment by juliasilge** [comment]
I believe we have some good explanation for all models we use now, but please feel free to open a new issue if something is not enough or unclear. 👍
