### ISSUE TITLE
Extra material for Intro course

### ISSUE THREAD

**Issue by hfrick** [tidymodels/workshops#218]
Candidates:

- [x] intro to feature engineering with recipes
- [x] grid search with tune
- [x] vetiver? see #167
- [ ] parsnip extension packages?
- [x] initial_time_split() section? see #175

**Comment by EmilHvitfeldt** [comment]
Ref: https://github.com/tidymodels/workshops/pull/233

**Comment by EmilHvitfeldt** [comment]
Workflowsets extra slides: https://github.com/tidymodels/workshops/pull/238

**Comment by hfrick** [comment]
Minimal intro to tuning via grid search: #239

**Comment by EmilHvitfeldt** [comment]
Time based splitting: https://github.com/tidymodels/workshops/pull/243

**Comment by hfrick** [comment]
update: We've also moved workflowsets into "extras" and we are going to move grid search into the planned content section.
