### ISSUE TITLE
update package list with the pkgs for advances extras

### ISSUE THREAD

**Issue by topepo** [tidymodels/workshops#225]
There are a few missing that are associated with the extra materials

**Comment by simonpcouch** [comment]
I see embed and rules. Slides use leaflet and countdown with `echo: false`.

The dependency heaviness of the embed install makes me wonder if we _should_ split out the installation instructions by the workshop. embed itself is a pretty quick install, but we'd likely want to install the [Suggests](https://github.com/tidymodels/embed#installation) needed by the used steps—I think that's just lme4 that's needed, which is the lighter of that set.

Related to #240.
