### ISSUE TITLE
Update landing site

### ISSUE THREAD

**Issue by hfrick** [tidymodels/workshops#229]
to reflect that there are now two workshops

- [x] Welcome
- [x] Is this workshop for me?
- [x] Preparation: packages to install
- [ ] Slides: Intro/Outro
- [x] Past workshops: add link to NYR archive

**Comment by EmilHvitfeldt** [comment]
>  add link to NYR archive

The NYR archive link is present as far as I can see https://workshops.tidymodels.org/#past-workshops. Unless you mean something else with this bullet

**Comment by hfrick** [comment]
Note for updating the "Is this workshop for me?" section: 
We could/should include an example for what we mean by "basic statistical concepts", maybe along the lines of "should have previously used `lm()` or `glm()` to create basic models".

**Comment by hfrick** [comment]
intro slides for advanced course in  #246

left to do: outro slides!
