### ISSUE TITLE
Audit extra deck on recipes for `forested`

### ISSUE THREAD

**Issue by hfrick** [tidymodels/workshops#308]
Amongst other things, this note from the first pass at updating things to use `forested`

              We should look into whether this transformation is actually helpful and choose another variable / step if not.

_Originally posted by @simonpcouch in https://github.com/tidymodels/workshops/pull/305#discussion_r1684619571_

**Comment by simonpcouch** [comment]
Notes from spending some time with this:

* The slides are generally quite generic and wouldn't need a major refactor.
* The slide on dates and exercise `What other transformations could we do with the raw time variable?` aren't relevant unless we read in a "raw" version of the dataset and convert it to dates.
* The `step_unknown()` step adds two zero-variance columns that are then removed by `step_zv()`.
