### ISSUE TITLE
Include Brier score in "Evaluating models" deck

### ISSUE THREAD

**Issue by hfrick** [tidymodels/workshops#310]
From https://github.com/tidymodels/workshops/pull/305#discussion_r1687918056

>  It would be nice to include the Brier score since it's now one of the default metrics in tune, no?

**Comment by simonpcouch** [comment]
Also noting that the classwork prompts folks to calculate it as an additional (I think) metric:

> https://github.com/tidymodels/workshops/blob/aaf582c55461df009ad174ba1b7b70128f004127/classwork/intro-04-classwork.qmd#L107
