### ISSUE TITLE
include "AI" in discussion of "What is machine learning"?

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/workshops#314]
Should we include some discussion of GenAI / LLMs in the discussion of how the workshop is scoped?

https://github.com/tidymodels/workshops/blob/550441ade794dd047540b93b2506c52ee870da29/slides/intro-01-introduction.qmd#L148

In the UW talk, I framed this as "BYO Venn Diagram"

https://github.com/simonpcouch/tidymodels-uw-2023/blob/d4da328e025b099a81682ca69fa1f5f9acb6fabf/index.qmd#L173-L175

**Comment by hfrick** [comment]
https://imgflip.com/i/8xy73a
