### ISSUE TITLE
Deck 1 - Finalize workshop policies

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/workshops#44]
Any final tweaking, plus "whatever we are saying about masking" - see the last bullet in the slide
<img width="1776" alt="Screen Shot 2022-07-12 at 10 28 40 AM" src="https://user-images.githubusercontent.com/19150088/178514549-f6cf507d-7716-46f4-bfc3-ff130e66233e.png">

**Comment by juliasilge** [comment]
Add survey link to Deck 7
