### ISSUE TITLE
Maybe include a slide in deck 6 to talk about boosted tree vs random forest

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/workshops#54]
i.e. both are built from decision trees, but one builds sequentially improving trees and the other builds independent trees

I think we could use a single slide that just has an image on it like this one from this article
https://medium.com/geekculture/xgboost-versus-random-forest-898e42870f30

I quite like this image actually

![](https://miro.medium.com/max/1400/1*6n0rqLRc8ljOsNlQ2Z5xug.png)

**Comment by topepo** [comment]
The right-hand side is incorrect. We don't do bootstrapping with boosting. There can be some sub-sampling but it would be irregular to bootstrap the data.

**Comment by DavisVaughan** [comment]
With boosting the idea is to upweight the data points that you predicted incorrectly in the previous iteration right?

**Comment by topepo** [comment]
Upweight for some, downweight for others but yeah. That's how it makes the trees different. There is probably some implementation out there that does add bootstrapping but that's not canonically how it works.
