### ISSUE TITLE
Have an intuitive visual description of what degrees of freedom means

### ISSUE THREAD

**Issue by dgrtwo** [tidymodels/workshops#81]
In the tuning slides, I think a visual depiction would help learners grasp what the degrees of freedom means for a model.

Here are two ideas:

*Include this image from your book* as a slide (with a talk track about "how bendy" it is):

![image](https://user-images.githubusercontent.com/994718/180582376-31d34d29-bd01-4cbc-86e1-bb27be8af8d1.png)

*Visualize how the effect of distance to goal is nonlinear*, with a plot like this one:

```
example_data <- nhl_train %>% 
  mutate(distance = sqrt((89 - abs(coord_x))^2 + abs(coord_y)^2))

example_data %>%
  group_by(distance = cut(distance, c(0, seq(10, 60, 5), 100))) %>%
  summarize(pct_on_goal = mean(on_goal == "yes"), n = n()) %>%
  mutate(distance = fct_recode(distance, "<10" = "(0,10]", ">60" = "(60,100]")) %>%
  ggplot(aes(distance, pct_on_goal)) +
  geom_line(group = 1, size = 2) +
  scale_y_continuous(labels = scales::percent) +
  expand_limits(y = 0) +
  labs(x = "Distance to goal (bucketed)",
       y = "% of shots in this bucket that are on goal")
```

![image](https://user-images.githubusercontent.com/994718/180582308-9edd583b-cd5f-4766-8187-7d1c86b6a962.png)

cc @juliasilge

**Comment by juliasilge** [comment]
I will work on this tomorrow (Saturday) and add them to the tuning slides 👍
