### ISSUE TITLE
prep and bake

### ISSUE THREAD

**Issue by jonthegeek** [tidymodels/workshops#97]
There were a lot of questions about how to see the results of the recipe (around slide 25 of 05). It might be helpful to show a slide about `prep` and `bake(new_data = NULL)`.

**Comment by EmilHvitfeldt** [comment]
We do have a slide about prep() and bake() at the end of that slide-deck page 52 https://workshops.tidymodels.org/slides/05-feature-engineering.html#/debugging-a-recipe

**Comment by jonthegeek** [comment]
I thought it was there somewhere! I think @topepo wanted this issue to consider moving it earlier in the deck.

**Comment by topepo** [comment]
Added in #100
